### ISSUE TITLE
Update huggingface nemo docker version

### ISSUE THREAD

**Issue by Theodotus1243** [huggingface/api-inference-community#122]
**Is your feature request related to a problem? Please describe.**
Squeezeformer arcitecture support was added in `nemo_toolkit==1.12.0`
But looks like huggingface docker has `nemo_toolkit==1.10.0`

Without it, I can't tun my model via inference API
https://huggingface.co/theodotus/stt_uk_squeezeformer_ctc_ml

**Describe the solution you'd like**
Here in nemo docker images there is no precise version of nemo to install
So it's server side docker conteiner update required 
https://github.com/huggingface/api-inference-community/tree/main/docker_images/nemo

**Comment by osanseviero** [comment]
cc @Narsil could you help re-triggering a build for nemo please? :pray:
