### ISSUE TITLE
Large models stuck on "Model xxxxx is is currently loading"

### ISSUE THREAD

**Issue by Eytan-S** [huggingface/api-inference-community#137]
Hi,

I'm trying to use the API for inference on some of the available models and it seems like they're stuck during loading.
I am using the "wait_for_model" parameter but it doesn't seem to work.
example:
`API_URL = "https://api-inference.huggingface.co/models/allenai/unifiedqa-t5-11b"
headers = {"Authorization": f"Bearer {API_TOKEN}"}

output = query({
    "inputs": "The answer to the universe is",
    "wait_for_model": True
})

output`

gives:
`{'error': 'Model allenai/unifiedqa-t5-11b is currently loading',
 'estimated_time': 1809.1820068359375}`

Subsequent queries fails the same way, with the same estimated_time.

Thanks,
Eytan

**Comment by osanseviero** [comment]
Hi there!

The model seems to be 45.2GB which is too large for the API to handle. Unfortunately, the API can only load models of up to 10GB. This ensures the model loads quickly and can run fast inference. cc @Narsil can comment more.

Thank you,
Omar

**Comment by Eytan-S** [comment]
Got it, thank you.

**Comment by Narsil** [comment]
Yes, actually we need to fix the message, the message should say the model should not load.

It should be there, so something is wrong.

**Comment by kyleliang919** [comment]
the error still persists, I don't think this should be closed. Also GPT-NeoX is 20B, why its inference is working?

**Comment by Narsil** [comment]
Because we have a special setup for it. 
 
 This is a model-per-model basis since those large models require specific setup, usually larger GPUs for instance.

**Comment by snayan06** [comment]
import requests

API_URL = "https://api-inference.huggingface.co/models/togethercomputer/RedPajama-INCITE-7B-Instruct"
headers = {"Authorization": "Bearer secretkey"}

def query(payload):
	response = requests.post(API_URL, headers=headers, json=payload)
	return response.json()

output = query({
	"inputs": "Can you please let us know more details about your ",
})

for this model , also getting the same , error seeing this one is closed . but what should i do for cases like this ?
error :
`{'error': 'Model togethercomputer/RedPajama-INCITE-7B-Instruct is currently loading',
 'estimated_time': 20.0}`
