### ISSUE TITLE
question re spaces API output length

### ISSUE THREAD

**Issue by i-am-neo** [huggingface/api-inference-community#227]
Hi @Narsil, please Let me know if I should post elsewhere if this is not the right place to ask - I couldn't find an answer in discussions nor in the docs so am starting here.

How can one specify a longer output length from a spaces API?

For example, for few shot prompting, I'd like to get a longer length in the output for Flan-T5-XL.
I've tried guess-fiddling with various permutations of "max_length" as below, to no effect of course.

Suggestions?

>   text = "a rather long few shot prompt"
>   response = requests.post("https://dzmltzack-flan-t5-xl-32bit-lm.hf.space/run/predict", json={
> 	"data": [
> 		text,
> 	  ],
>     "parameters": {"max_length": 300, "max_new_tokens": 300},
>     "tokenizer_kwargs": {"max_length": 300, "max_new_tokens": 300},
>   }).json()

I'd like as output an output text of long length.
Thanks.

**Comment by Narsil** [comment]
Hi, I am not sure.

-you can check the code of the space to check app.py and see how it's implemented.
- maybe the model is outputting eos token and thus stopping the generation naturally.
- then I see you are sending parameters which I assume is targeting the API, but I'm not sure they are flowing correctly within the space. Maybe try verifying that part.

**Comment by i-am-neo** [comment]
Thanks for your response. It's not my space... I've asked the author (nothing in app.py).

If you have other suggestions, please let me know.  Otherwise, I can close this issue (or you can).

**Comment by Narsil** [comment]
Ohh , the limit is 256 for the API might be what he meant.

**Comment by Narsil** [comment]
Unfortunately no. We have to have some limits on free inferencing.

You can run the inference in the space and use a GPU to have entire freedom.
Flan-t5-xxl still should have higher limits than this

**Comment by i-am-neo** [comment]
Ok thanks.
