### ISSUE TITLE
Add image feature extraction to the Inference API [img2vec]

### ISSUE THREAD

**Issue by avivhu** [huggingface/api-inference-community#229]
# **Is your feature request related to a problem? Please describe.**
I'm working on a "search by image" prototype. I implemented image search in the standard way:
#### Prepare search index (offline)
   1. [Extract image features](https://huggingface.co/docs/timm/feature_extraction)
   2. Create index for vector search (e.g., with FAISS)
#### Search by image (online)
   3. Extract image features from query image
   4. Look up nearest vector in index

# **Describe the solution you'd like**
I'd like to use HuggingFace Inference API to extract features from searched images (no. 3 above). I see we can extract text features with some models (text2vec) but there is no img2vec support.

# **Describe alternatives you've considered**
1. I considered renting a VM or running a Docker on Azure for the image feature extraction, but it's expensive for GPU enabled options. All I need is very light GPU usage (about 10 ms per search) and it doesn't make sense to allocate a VM for an entire month for a tiny sliver of actual usage.

2. I considered using a HuggingFace Spaces for the app, but I need the options to store the query images and other customizations.

# **Additional context**
Note that I built the image index offline (no. 1-2 above), and that isn't the intended use of Inference API. I need Inference API for the online component: image search.

**Comment by radames** [comment]
hi @avivhu thanks for bringing this up.
In all cases, we can always implement a custom pipeline, I've fixed your original requested model and now it works, https://huggingface.co/radames/blip_image_embeddings

Here is a template for generic custom pipelines, feel free to build other models and pipelines with that task

https://huggingface.co/templates/feature-extraction/tree/main

**Comment by MattiaSangermano** [comment]
Hi @radames, I am also facing the same problem. I was wondering if there was a way to use a pipeline for feature extraction on images without having to create a repository on Huggingface every time I change the embedding model. I'm looking for a model-agnostic solution such as the text feature-extraction pipeline (`https://api-inference.huggingface.co/pipeline/feature-extraction/{model_id}`)
