### ISSUE TITLE
Run production grade private models

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [huggingface/api-inference-community#26]
Hello,

Following discussion with @Narsil, he told me that actually model hub is not meant to be able to load private models (as of now), since the api-inference-community was originally intended to promote community libraries that use the hub.

However, in the scope of running production grade private models would it be possible to internally discuss this possibility within model hub?

Thanks!

**Comment by david429429** [comment]
Tea por

**Comment by Narsil** [comment]
@david429429 I'm closing this very old thread.

If you want production grade inference, you should try `spaces` (free form inference) or `hf-endpoints` (something closer to what is here, with actually also free form but much simpler to setup if you just want to deploy a given model).
