### ISSUE TITLE
Doesn't work with the bart-large-cnn model

### ISSUE THREAD

**Issue by LevaniVashadze** [huggingface/api-inference-community#288]
![image](https://github.com/huggingface/api-inference-community/assets/100613979/7bf405a7-d70b-454c-93a5-d7a1f0d6b190)
{'error': "Could not load model facebook/bart-large-cnn with any of the following classes: (<class 'transformers.models.bart.modeling_bart.BartForConditionalGeneration'>, <class 'transformers.models.bart.modeling_tf_bart.TFBartForConditionalGeneration'>)."}

**Comment by Narsil** [comment]
Should be fixed. Thanks for reporting ! 

This model was running some very old code, and internal changes killed it.
