### ISSUE TITLE
Hosted Inference Api, all models error 422

### ISSUE THREAD

**Issue by VatsaDev** [huggingface/api-inference-community#305]
I’ve tried multiple models on the inference api text-generation, including,

`BigScience/Bloom`
`tiiuae/falcon-7b-instruct`
`OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5`

Since all the models appear to be having this issue, I think it's something with the hosted api.  whats wrong?

**Comment by Narsil** [comment]
https://huggingface.co/OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5?text=%3C%7Cprompter%7C%3EWrite+a+story+about+future+of+AI+development%3C%7Cendoftext%7C%3E%3C%7Cassistant%7C%3E

Everything seems to be working fine...

Can you share your request and the full response ? https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422

**Comment by VatsaDev** [comment]
At the main website, its fine, but not on code.

code:

``` js
async function query(data) {
        const response = await fetch(
            "https://api-inference.huggingface.co/models/bigscience/bloom-560m",//falcon-7b-instruct
            {
                headers: { 
                    "Content-Type": "application/json",
                    Authorization: `Bearer {TOKEN}`
                },
                method: "POST",
                body: JSON.stringify(data),
            }
        );
        const result = await response.json();
        return result;
    }
```
![Screen Shot 2023-07-17 at 4 00 16 PM](https://github.com/huggingface/api-inference-community/assets/71975550/5130f396-d4a0-47c2-8d2b-8f6342373bdb)

**Comment by Narsil** [comment]
You're not actually sending correct JSON, try sending `'{"inputs": "Can you"}'` 

Note: You should probably invalidate your access token and use another one.

**Comment by Narsil** [comment]
```
body: {"inputs": data}
```
I think
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
Maybe `JSON.stringify({"inputs": data})`

**Comment by VatsaDev** [comment]
JSON.stringify({"inputs": data}) worked! thanks for everything!
