### ISSUE TITLE
Many of the docker images seem to be out of sync with latest inference community version

### ISSUE THREAD

**Issue by StephenHodgson** [huggingface/api-inference-community#326]
https://github.com/huggingface/api-inference-community/blob/3ad052ea9d4ca913dd6064cbf2326a959f513e46/docker_images/espnet/requirements.txt#L1

**Comment by StephenHodgson** [comment]
I feel like that they should be kept up to date, esp with changes made recently to accept header usages in #287

**Comment by Narsil** [comment]
Ping the relevant maintainers if you want.
But no, the API is not intended to be a product, so keeping up-to-date is not something we want to commit to.

**Comment by StephenHodgson** [comment]
> Ping the relevant maintainers if you want.

I'm still not sure how to accomplish this, let alone figure out who to contact

**Comment by osanseviero** [comment]
Hi there! If you would like to upgrade the version of a specific library for a specific reason (e.g. missing params), feel free to open a PR to do the version bump
