### ISSUE TITLE
meta-llama/Llama-2-70b-chat-hf Inference API shows incpmplete output

### ISSUE THREAD

**Issue by omarnj-lab** [huggingface/api-inference-community#332]
Hello community, 

I need an urgent help with the inference API of the meta-llama/Llama-2-70b-chat-hf. I have subscrbied with pro in huggingface and when I tried to use the inference api, it shows incomplete responce and I am still wondering why !! 

I am using the following ınference API pythoc script: 

`import requests

API_URL = "https://api-inference.huggingface.co/models/meta-llama/Llama-2-70b-chat-hf"
headers = {"Authorization": "Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx"}

def query(payload):
	response = requests.post(API_URL, headers=headers, json=payload)
	return response.json()
	
output = query({
	"inputs": "Can you please let us know more details about your ",
})`

Hop you can answer ne ASAP

**Comment by Narsil** [comment]
What do you mean incomplete ?

Here you are not specifying `{"inputs": "Can..", "parameters": {"max_new_tokens": 100}}`. `max_new_tokens` is how long the generation can be. I think the default is currently 20, which might explain "incomplete" generation.

You could also potentially support `{"inputs": "Can..", "parameters": {"max_new_tokens": 100}, "stream": True}` to get live inference.

**Comment by stefanache** [comment]
can halp me because I received the following  error:

{'error': 'Authorization header is correct, but the token seems invalid'}
