### ISSUE TITLE
Proper parameters for `HuggingFaceM4/idefics-9b-instruct`

### ISSUE THREAD

**Issue by KastanDay** [huggingface/api-inference-community#336]
**Is your feature request related to a problem? Please describe.**
Although the Hub says that InferenceAPI ["is turned off for this model"](https://huggingface.co/HuggingFaceM4/idefics-9b-instruct) **it still appears to load & work** (see the example below). 

My question, how do I input both text AND an image to the model? It will only accept a single prompt from me, and it works with text but it won't read any of my images. 

**Describe the solution you'd like**
A spec/schema for how to call the API, like [those documented in the API-reference](https://huggingface.co/docs/api-inference/etailed_parameters#computer-vision).

**Describe alternatives you've considered**
I'll next try a paid API Endpoint to attempt to learn the expected schema for calling the model. 

**Additional context**
**I'm able to call the model**, but it only accepts text input: 
```python
import json
import requests
import base64

img_url = "https://upload.wikimedia.org/wikipedia/commons/8/86/Id%C3%A9fix.JPG"
API_URL = "https://api-inference.huggingface.co/models/HuggingFaceM4/idefics-9b-instruct" 
headers = {
    "Authorization": f"Bearer {HF_TOKEN}",
    "Content-Type": "application/json"
}

def query(image_url):
    response = requests.get(image_url)
    image_bytes = response.content
    encoded_image = base64.b64encode(image_bytes).decode('utf-8')
    data = {
        "inputs": img_url,
            # "prompt": "What's in this image?",
            # "prompt": encoded_image
        # }
        # "image": encoded_image,
        # "inputs": "What's in this image?",
    }
    json_data = json.dumps(data)
    print("my request", json_data)
    response = requests.request("POST", API_URL, headers=headers, data=json_data)
    print("Response content:", response.content)
    return json.loads(response.content.decode("utf-8"))

print(query(img_url))

## The results seem nearly there! 
## [{'generated_text': 'https://upload.wikimedia.org/wikipedia/commons/8/86/Id%C3%A9fix.JPGScooby-Doo, Where Are You!'}]
```

**Comment by Narsil** [comment]
Just send regular text. The images you should send in markdown inline format `![](URL)` Those will get picked up by the inference.
