### ISSUE TITLE
Inference API always returns error: Invalid token

### ISSUE THREAD

**Issue by greyblue9** [huggingface/api-inference-community#38]
Sorry if this is not the best place to post this issue. I am having an issue with the inference API suddenly, after it has worked perfectly for months:

After seeing '{ "error": "invalid token" }' coming back in response to queries, I created a new API token (old one was not showing up, abd changed the header from `Authorization: Bearer api_XXX` to `Authorization: Bearer hf_YYY`  as outlined in the docs, but am still facing the same error.

Any idea what could be the issue? I am so hoping this could be fixed soon.

**Comment by greyblue9** [comment]
> Hi @greyblue9 ,
> Both old and new tokens should work the same way by the way.
Thank you so much for your response. I actually created a new account with a new (write) token,  and that worked 🤔

**Comment by Narsil** [comment]
Probably, we really need to get `Bearer {API_TOKEN}` !

Glad you could work it out.

**Comment by Narsil** [comment]
I will close this, don ´t hesitate to open again if you think it's incorrect.
