### ISSUE TITLE
Remove unimplemented pipelines across the different integrations

### ISSUE THREAD

**Issue by nateraw** [huggingface/api-inference-community#47]
**Is your feature request related to a problem? Please describe.**
Is there any reason why we have a ton of unused pipeline files across the different integrations ([example](https://github.com/huggingface/api-inference-community/blob/main/docker_images/asteroid/app/pipelines/image_classification.py))? I think it would be a lot easier to both navigate the repo and quickly see which integrations have which pipelines enabled if we only included the files that are actually being used. 

**Describe the solution you'd like**
- [ ] Remove unused pipeline files from the different integrations.
- [ ] Update guidance in contributing docs if need be to reflect the fact we shouldn't be copying over all the pipeline template files.

WDYT?

**Comment by osanseviero** [comment]
Yes please. We've done this for new integrations but old ones still keep lots of unused code. I'm 👍for this. Would you like to open a PR for it?

**Comment by nateraw** [comment]
Sure! Will do
