### ISSUE TITLE
fastai models leading to an internal server error

### ISSUE THREAD

**Issue by omarespejel** [huggingface/api-inference-community#58]
# Description
fastai image classification models leading to an internal server error (photo below). PR #49.

Follow-up responsibility of @omarespejel.

<img width="641" alt="image" src="https://user-images.githubusercontent.com/4755430/170802247-cb5a9b73-4b55-4f3a-aa0c-da707f69765d.png">

**Comment by osanseviero** [comment]
This is still not deployed, which leads to this error

**Comment by omarespejel** [comment]
Thank you @osanseviero! 🤗
